theme: jekyll-theme-minimal
title: Brooke Laird's Portfolio
avatar: "bio-photo.HEIC"
description: Hi there! My name is Brooke and I am a senior Geography and Environmental Studies major at Middlebury College. I am passionate about using GIS, remote sensing techniques, and cartographic design to expand on studies of environmental justice, climate change adaptation, and landcover change. On this page you will find my work from various courses, independent study, and research positions.
